// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj0HhSK3L3Xi9GcBWRM0xlfAZU5UETTmI',
    appId: '1:385272013310:web:4897a361d9e65cf2e260af',
    messagingSenderId: '385272013310',
    projectId: 'atw-task-d1041',
    authDomain: 'atw-task-d1041.firebaseapp.com',
    storageBucket: 'atw-task-d1041.firebasestorage.app',
    measurementId: 'G-XFN0WWCCR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh65R4e-H2otV8cakchCaBIRM1k_QrYiE',
    appId: '1:385272013310:android:c6c0232af0c1a4bce260af',
    messagingSenderId: '385272013310',
    projectId: 'atw-task-d1041',
    storageBucket: 'atw-task-d1041.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKom-BZOA6JpyPTz86yopMgaKNeb84s6Y',
    appId: '1:385272013310:ios:52cb2a6138ba5865e260af',
    messagingSenderId: '385272013310',
    projectId: 'atw-task-d1041',
    storageBucket: 'atw-task-d1041.firebasestorage.app',
    androidClientId: '385272013310-obf07eb2uq29jonljgjr4m8c1jv56it9.apps.googleusercontent.com',
    iosClientId: '385272013310-t7fj3ftcgiampdg9pk1a8k3vo6i1nmep.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKom-BZOA6JpyPTz86yopMgaKNeb84s6Y',
    appId: '1:385272013310:ios:52cb2a6138ba5865e260af',
    messagingSenderId: '385272013310',
    projectId: 'atw-task-d1041',
    storageBucket: 'atw-task-d1041.firebasestorage.app',
    androidClientId: '385272013310-obf07eb2uq29jonljgjr4m8c1jv56it9.apps.googleusercontent.com',
    iosClientId: '385272013310-t7fj3ftcgiampdg9pk1a8k3vo6i1nmep.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj0HhSK3L3Xi9GcBWRM0xlfAZU5UETTmI',
    appId: '1:385272013310:web:ebd9cd2c528054e5e260af',
    messagingSenderId: '385272013310',
    projectId: 'atw-task-d1041',
    authDomain: 'atw-task-d1041.firebaseapp.com',
    storageBucket: 'atw-task-d1041.firebasestorage.app',
    measurementId: 'G-5ZNL2CMMMN',
  );
}
